// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by configure this by running the '
          'FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2EJEIVTTFRguw-4UAhs9U0nmxHhaGL0U',
    appId: '1:840212482870:web:placeholder',
    messagingSenderId: '840212482870',
    projectId: 'localnest-7eada',
    authDomain: 'localnest-7eada.firebaseapp.com',
    databaseURL: 'https://localnest-7eada.firebaseio.com',
    storageBucket: 'localnest-7eada.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2EJEIVTTFRguw-4UAhs9U0nmxHhaGL0U',
    appId: '1:840212482870:android:ace5dcc68aa841ad27c197',
    messagingSenderId: '840212482870',
    projectId: 'localnest-7eada',
    databaseURL: 'https://localnest-7eada.firebaseio.com',
    storageBucket: 'localnest-7eada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2EJEIVTTFRguw-4UAhs9U0nmxHhaGL0U',
    appId: '1:840212482870:ios:placeholder',
    messagingSenderId: '840212482870',
    projectId: 'localnest-7eada',
    databaseURL: 'https://localnest-7eada.firebaseio.com',
    storageBucket: 'localnest-7eada.firebasestorage.app',
    iosBundleId: 'com.example.local_nest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2EJEIVTTFRguw-4UAhs9U0nmxHhaGL0U',
    appId: '1:840212482870:ios:placeholder',
    messagingSenderId: '840212482870',
    projectId: 'localnest-7eada',
    databaseURL: 'https://localnest-7eada.firebaseio.com',
    storageBucket: 'localnest-7eada.firebasestorage.app',
    iosBundleId: 'com.example.local_nest',
  );
}